//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharmEvents.DAL.WCF.Client.CharmEventsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CharmEventsService.ICharmEventsService")]
    public interface ICharmEventsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICharmEventsService/GetUserInfo", ReplyAction="http://tempuri.org/ICharmEventsService/GetUserInfoResponse")]
        System.Collections.Generic.List<CharmEvents.Database.Database.ResultInfo> GetUserInfo(CharmEvents.Database.Database.UserInfo userinfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICharmEventsService/UsersExchangePackets", ReplyAction="http://tempuri.org/ICharmEventsService/UsersExchangePacketsResponse")]
        CharmEvents.Database.Database.ResultInfo UsersExchangePackets(CharmEvents.Database.Database.UserInfo userinfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICharmEventsService/UsersDrawPackets", ReplyAction="http://tempuri.org/ICharmEventsService/UsersDrawPacketsResponse")]
        CharmEvents.Database.Database.ResultInfo UsersDrawPackets(CharmEvents.Database.Database.UserInfo userinfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICharmEventsService/UsersLoginPacket", ReplyAction="http://tempuri.org/ICharmEventsService/UsersLoginPacketResponse")]
        CharmEvents.Database.Database.ResultInfo UsersLoginPacket(CharmEvents.Database.Database.UserInfo userinfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICharmEventsService/GetRankListList", ReplyAction="http://tempuri.org/ICharmEventsService/GetRankListListResponse")]
        System.Collections.Generic.List<CharmEvents.Database.Database.RankList> GetRankListList(ref CommonLibs.Common.DataPage dp);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICharmEventsServiceChannel : CharmEvents.DAL.WCF.Client.CharmEventsService.ICharmEventsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CharmEventsServiceClient : System.ServiceModel.ClientBase<CharmEvents.DAL.WCF.Client.CharmEventsService.ICharmEventsService>, CharmEvents.DAL.WCF.Client.CharmEventsService.ICharmEventsService {
        
        public CharmEventsServiceClient() {
        }
        
        public CharmEventsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CharmEventsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CharmEventsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CharmEventsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<CharmEvents.Database.Database.ResultInfo> GetUserInfo(CharmEvents.Database.Database.UserInfo userinfo) {
            return base.Channel.GetUserInfo(userinfo);
        }
        
        public CharmEvents.Database.Database.ResultInfo UsersExchangePackets(CharmEvents.Database.Database.UserInfo userinfo) {
            return base.Channel.UsersExchangePackets(userinfo);
        }
        
        public CharmEvents.Database.Database.ResultInfo UsersDrawPackets(CharmEvents.Database.Database.UserInfo userinfo) {
            return base.Channel.UsersDrawPackets(userinfo);
        }
        
        public CharmEvents.Database.Database.ResultInfo UsersLoginPacket(CharmEvents.Database.Database.UserInfo userinfo) {
            return base.Channel.UsersLoginPacket(userinfo);
        }
        
        public System.Collections.Generic.List<CharmEvents.Database.Database.RankList> GetRankListList(ref CommonLibs.Common.DataPage dp) {
            return base.Channel.GetRankListList(ref dp);
        }
    }
}
