//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetFeedEvents.DAL.AdminWCF.Client.PetFeedEventsAdminService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PetFeedEventsAdminService.IPetFeedEventsAdminService")]
    public interface IPetFeedEventsAdminService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPetFeedEventsAdminService/CleanAllData", ReplyAction="http://tempuri.org/IPetFeedEventsAdminService/CleanAllDataResponse")]
        int CleanAllData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPetFeedEventsAdminService/GetGameDailyLogList", ReplyAction="http://tempuri.org/IPetFeedEventsAdminService/GetGameDailyLogListResponse")]
        System.Collections.Generic.List<PetFeedEvents.Database.Database.GameDailyLog> GetGameDailyLogList(ref CommonLibs.Common.DataPage dp, PetFeedEvents.Database.Database.GameDailyLog searchGameDailyLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPetFeedEventsAdminService/GetDynamicPacketQueueList", ReplyAction="http://tempuri.org/IPetFeedEventsAdminService/GetDynamicPacketQueueListResponse")]
        System.Collections.Generic.List<PetFeedEvents.Database.Database.DynamicPacketQueue> GetDynamicPacketQueueList(ref CommonLibs.Common.DataPage dp, PetFeedEvents.Database.Database.DynamicPacketQueue searchDynamicPacketQueue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPetFeedEventsAdminService/InsertGameDailyLog", ReplyAction="http://tempuri.org/IPetFeedEventsAdminService/InsertGameDailyLogResponse")]
        int InsertGameDailyLog(PetFeedEvents.Database.Database.GameDailyLog gamedailylog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPetFeedEventsAdminService/GetDynamicPacketQueueLogList", ReplyAction="http://tempuri.org/IPetFeedEventsAdminService/GetDynamicPacketQueueLogListRespons" +
            "e")]
        System.Collections.Generic.List<PetFeedEvents.Database.Database.DynamicPacketQueueLog> GetDynamicPacketQueueLogList(ref CommonLibs.Common.DataPage dp, PetFeedEvents.Database.Database.DynamicPacketQueueLog searchDynamicPacketQueueLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPetFeedEventsAdminService/GetTaskConfig", ReplyAction="http://tempuri.org/IPetFeedEventsAdminService/GetTaskConfigResponse")]
        System.Collections.Generic.List<PetFeedEvents.Database.Database.TaskConfig> GetTaskConfig(ref CommonLibs.Common.DataPage dp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPetFeedEventsAdminService/InsertTaskConfig", ReplyAction="http://tempuri.org/IPetFeedEventsAdminService/InsertTaskConfigResponse")]
        int InsertTaskConfig(PetFeedEvents.Database.Database.TaskConfig taskconfig);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPetFeedEventsAdminService/UpdateTaskConfig", ReplyAction="http://tempuri.org/IPetFeedEventsAdminService/UpdateTaskConfigResponse")]
        int UpdateTaskConfig(PetFeedEvents.Database.Database.TaskConfig taskconfig);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPetFeedEventsAdminService/DeleteTaskConfig", ReplyAction="http://tempuri.org/IPetFeedEventsAdminService/DeleteTaskConfigResponse")]
        int DeleteTaskConfig(PetFeedEvents.Database.Database.TaskConfig taskconfig);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPetFeedEventsAdminServiceChannel : PetFeedEvents.DAL.AdminWCF.Client.PetFeedEventsAdminService.IPetFeedEventsAdminService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PetFeedEventsAdminServiceClient : System.ServiceModel.ClientBase<PetFeedEvents.DAL.AdminWCF.Client.PetFeedEventsAdminService.IPetFeedEventsAdminService>, PetFeedEvents.DAL.AdminWCF.Client.PetFeedEventsAdminService.IPetFeedEventsAdminService {
        
        public PetFeedEventsAdminServiceClient() {
        }
        
        public PetFeedEventsAdminServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PetFeedEventsAdminServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PetFeedEventsAdminServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PetFeedEventsAdminServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CleanAllData() {
            return base.Channel.CleanAllData();
        }
        
        public System.Collections.Generic.List<PetFeedEvents.Database.Database.GameDailyLog> GetGameDailyLogList(ref CommonLibs.Common.DataPage dp, PetFeedEvents.Database.Database.GameDailyLog searchGameDailyLog) {
            return base.Channel.GetGameDailyLogList(ref dp, searchGameDailyLog);
        }
        
        public System.Collections.Generic.List<PetFeedEvents.Database.Database.DynamicPacketQueue> GetDynamicPacketQueueList(ref CommonLibs.Common.DataPage dp, PetFeedEvents.Database.Database.DynamicPacketQueue searchDynamicPacketQueue) {
            return base.Channel.GetDynamicPacketQueueList(ref dp, searchDynamicPacketQueue);
        }
        
        public int InsertGameDailyLog(PetFeedEvents.Database.Database.GameDailyLog gamedailylog) {
            return base.Channel.InsertGameDailyLog(gamedailylog);
        }
        
        public System.Collections.Generic.List<PetFeedEvents.Database.Database.DynamicPacketQueueLog> GetDynamicPacketQueueLogList(ref CommonLibs.Common.DataPage dp, PetFeedEvents.Database.Database.DynamicPacketQueueLog searchDynamicPacketQueueLog) {
            return base.Channel.GetDynamicPacketQueueLogList(ref dp, searchDynamicPacketQueueLog);
        }
        
        public System.Collections.Generic.List<PetFeedEvents.Database.Database.TaskConfig> GetTaskConfig(ref CommonLibs.Common.DataPage dp) {
            return base.Channel.GetTaskConfig(ref dp);
        }
        
        public int InsertTaskConfig(PetFeedEvents.Database.Database.TaskConfig taskconfig) {
            return base.Channel.InsertTaskConfig(taskconfig);
        }
        
        public int UpdateTaskConfig(PetFeedEvents.Database.Database.TaskConfig taskconfig) {
            return base.Channel.UpdateTaskConfig(taskconfig);
        }
        
        public int DeleteTaskConfig(PetFeedEvents.Database.Database.TaskConfig taskconfig) {
            return base.Channel.DeleteTaskConfig(taskconfig);
        }
    }
}
