//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampEventsDALTEST.CampEventsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CampEventsService.ICampEventsService")]
    public interface ICampEventsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICampEventsService/UserChooseCamp", ReplyAction="http://tempuri.org/ICampEventsService/UserChooseCampResponse")]
        int UserChooseCamp(CampEvents.Database.Database.UserCampLog usercamplog);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICampEventsServiceChannel : CampEventsDALTEST.CampEventsService.ICampEventsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CampEventsServiceClient : System.ServiceModel.ClientBase<CampEventsDALTEST.CampEventsService.ICampEventsService>, CampEventsDALTEST.CampEventsService.ICampEventsService {
        
        public CampEventsServiceClient() {
        }
        
        public CampEventsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CampEventsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CampEventsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CampEventsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int UserChooseCamp(CampEvents.Database.Database.UserCampLog usercamplog) {
            return base.Channel.UserChooseCamp(usercamplog);
        }
    }
}
