//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeaponDesign.DAL.WCF.Client.WeaponDesignService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WeaponDesignService.IWeaponDesignService")]
    public interface IWeaponDesignService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeaponDesignService/AddUserList", ReplyAction="http://tempuri.org/IWeaponDesignService/AddUserListResponse")]
        int AddUserList(WeaponDesign.Database.Database.UserList userList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeaponDesignService/AddWeaponList", ReplyAction="http://tempuri.org/IWeaponDesignService/AddWeaponListResponse")]
        int AddWeaponList(WeaponDesign.Database.Database.WeaponList weaponList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeaponDesignService/UpdateWeaponList", ReplyAction="http://tempuri.org/IWeaponDesignService/UpdateWeaponListResponse")]
        int UpdateWeaponList(WeaponDesign.Database.Database.WeaponList weaponList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeaponDesignService/UpdateWeaponStatus", ReplyAction="http://tempuri.org/IWeaponDesignService/UpdateWeaponStatusResponse")]
        int UpdateWeaponStatus(WeaponDesign.Database.Database.WeaponList weaponList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeaponDesignService/GetWeaponUserList", ReplyAction="http://tempuri.org/IWeaponDesignService/GetWeaponUserListResponse")]
        System.Collections.Generic.List<WeaponDesign.Database.Database.WeaponUserList> GetWeaponUserList(WeaponDesign.Database.Database.WeaponUserList weaponuserlist);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeaponDesignService/AddCommentsList", ReplyAction="http://tempuri.org/IWeaponDesignService/AddCommentsListResponse")]
        int AddCommentsList(WeaponDesign.Database.Database.CommentsList commentsList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeaponDesignService/GetWeaponCommentsList", ReplyAction="http://tempuri.org/IWeaponDesignService/GetWeaponCommentsListResponse")]
        System.Collections.Generic.List<WeaponDesign.Database.Database.WeaponComments> GetWeaponCommentsList(ref CommonLibs.Common.DataPage dp, WeaponDesign.Database.Database.WeaponComments searchWeaponComments);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeaponDesignService/AddPraiseLog", ReplyAction="http://tempuri.org/IWeaponDesignService/AddPraiseLogResponse")]
        int AddPraiseLog(WeaponDesign.Database.Database.PraiseLog praiseLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeaponDesignService/GetWeaponList", ReplyAction="http://tempuri.org/IWeaponDesignService/GetWeaponListResponse")]
        WeaponDesign.Database.Database.WeaponList GetWeaponList(WeaponDesign.Database.Database.WeaponList searchWeaponList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeaponDesignService/GetDesignEventType", ReplyAction="http://tempuri.org/IWeaponDesignService/GetDesignEventTypeResponse")]
        WeaponDesign.Database.Database.DesignEventType GetDesignEventType(WeaponDesign.Database.Database.DesignEventType searchDesignEventType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWeaponDesignServiceChannel : WeaponDesign.DAL.WCF.Client.WeaponDesignService.IWeaponDesignService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WeaponDesignServiceClient : System.ServiceModel.ClientBase<WeaponDesign.DAL.WCF.Client.WeaponDesignService.IWeaponDesignService>, WeaponDesign.DAL.WCF.Client.WeaponDesignService.IWeaponDesignService {
        
        public WeaponDesignServiceClient() {
        }
        
        public WeaponDesignServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WeaponDesignServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeaponDesignServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeaponDesignServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddUserList(WeaponDesign.Database.Database.UserList userList) {
            return base.Channel.AddUserList(userList);
        }
        
        public int AddWeaponList(WeaponDesign.Database.Database.WeaponList weaponList) {
            return base.Channel.AddWeaponList(weaponList);
        }
        
        public int UpdateWeaponList(WeaponDesign.Database.Database.WeaponList weaponList) {
            return base.Channel.UpdateWeaponList(weaponList);
        }
        
        public int UpdateWeaponStatus(WeaponDesign.Database.Database.WeaponList weaponList) {
            return base.Channel.UpdateWeaponStatus(weaponList);
        }
        
        public System.Collections.Generic.List<WeaponDesign.Database.Database.WeaponUserList> GetWeaponUserList(WeaponDesign.Database.Database.WeaponUserList weaponuserlist) {
            return base.Channel.GetWeaponUserList(weaponuserlist);
        }
        
        public int AddCommentsList(WeaponDesign.Database.Database.CommentsList commentsList) {
            return base.Channel.AddCommentsList(commentsList);
        }
        
        public System.Collections.Generic.List<WeaponDesign.Database.Database.WeaponComments> GetWeaponCommentsList(ref CommonLibs.Common.DataPage dp, WeaponDesign.Database.Database.WeaponComments searchWeaponComments) {
            return base.Channel.GetWeaponCommentsList(ref dp, searchWeaponComments);
        }
        
        public int AddPraiseLog(WeaponDesign.Database.Database.PraiseLog praiseLog) {
            return base.Channel.AddPraiseLog(praiseLog);
        }
        
        public WeaponDesign.Database.Database.WeaponList GetWeaponList(WeaponDesign.Database.Database.WeaponList searchWeaponList) {
            return base.Channel.GetWeaponList(searchWeaponList);
        }
        
        public WeaponDesign.Database.Database.DesignEventType GetDesignEventType(WeaponDesign.Database.Database.DesignEventType searchDesignEventType) {
            return base.Channel.GetDesignEventType(searchDesignEventType);
        }
    }
}
